### ISSUE TITLE
How to handle dependencies that are only used in test?

### ISSUE THREAD

**Issue by tcoopman** [sasa1977/boundaries#2]
I'm not sure how to handle `test/support/....` files.

In my `test/support` I sometimes add things to the same module structure for example:

lib/foo:
```elixir
module Foo do
end
```

test/support/factory.ex:
```elixir
module Foo.Factory do
end
```

Now Boundaries complains that `Foo.Factory` is not allowed from an other file in `test/support` (for example a helper file to setup some domain data).

Ideally I think I want to be able to say to ignore some files, or be able to change the boundaries for tests.

**Comment by sasa1977** [comment]
I believe that changes proposed in #5 (in particular, the section "Unclassified modules") should address this. Let me know what you think.

**Comment by sasa1977** [comment]
I added the first draft for supporting some ignore mechanism. You can take a look at the idea [here](https://github.com/sasa1977/boundaries/blob/1032db761bcca1da9a6aa8705f889ce12bd9c848/lib/boundary.ex#L126-L185). Do you think something like this would suffice for this scenario?
